### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by snowell** [stardog-union/stardog-clj#6]
As pointed out on the community forums (https://community.stardog.com/t/clojure-stardog-and-stardog-clj/191) the readme for this library still references the `mavenInstall` script and almost certainly some other outdated things, and should be updated for 4.x or even 5.x

**Comment by snowell** [comment]
Should also update the server URLs from "snarl://localhost" to be HTTP, since snarl is deprecated and will be removed from 5.x

**Comment by joephayes** [comment]
Resolved by https://github.com/stardog-union/stardog-clj/commit/92dd617fb8d46e9b2f2bea578f01a8ef79c84b9f
